Traceback (most recent call last):
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/ml-latest/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X, y = train_generator[0]
print(X.shape)
print(y.shape)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-575090085654>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mX[0m[0;34m,[0m [0my[0m [0;34m=[0m [0mtrain_generator[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprint[0m[0;34m([0m[0mX[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0my[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/capstone-particle-physics-domain/capstone-particle-physics-domain/weeks/DataGenerator.py[0m in [0;36m__getitem__[0;34m(self, index)[0m
[1;32m     68[0m [0;34m[0m[0m
[1;32m     69[0m         [0;31m# Generate data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 70[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__data_generation[0m[0;34m([0m[0munique_files[0m[0;34m,[0m [0mstarts[0m[0;34m,[0m [0mstops[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     71[0m [0;34m[0m[0m
[1;32m     72[0m     [0;32mdef[0m [0mon_epoch_end[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/capstone-particle-physics-domain/capstone-particle-physics-domain/weeks/DataGenerator.py[0m in [0;36m__data_generation[0;34m(self, unique_files, starts, stops)[0m
[1;32m     88[0m                 [0mzs[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mz[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     89[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 90[0;31m                 [0mX[0m[0;34m,[0m [0my[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m__get_features_labels[0m[0;34m([0m[0mifile[0m[0;34m,[0m [0mstart[0m[0;34m,[0m [0mstop[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     91[0m             [0mXs[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mX[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     92[0m             [0mys[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0my[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/capstone-particle-physics-domain/capstone-particle-physics-domain/weeks/DataGenerator.py[0m in [0;36m__get_features_labels[0;34m(self, ifile, entrystart, entrystop)[0m
[1;32m    118[0m                                     [0mentrystart[0m[0;34m=[0m[0mentrystart[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    119[0m                                     [0mentrystop[0m[0;34m=[0m[0mentrystop[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 120[0;31m                                     namedecode='utf-8')
[0m[1;32m    121[0m [0;34m[0m[0m
[1;32m    122[0m         label_array_all = tree.arrays(branches=self.labels, 

[0;31mTypeError[0m: arrays() got an unexpected keyword argument 'branches'
TypeError: arrays() got an unexpected keyword argument 'branches'

